# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: registry-vpc.cn-beijing.aliyuncs.com/i-counting/karma:latest

# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
# stages:
#   - install
#   - test
#   - build
cache:
  paths:
  - node_modules
before_script:
  - yarn install
test:
  script:
    - yarn libs
    - yarn dist
    - yarn test
